<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lihat Program</name>
   <tag></tag>
   <elementGuidId>5799d9b9-5d0d-43b5-8cf8-874ae5d340dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f772d8f8-2d60-49b9-b505-81439b4874da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#section-lihat-program</value>
      <webElementGuid>f15df6bc-c318-4ba6-bc2c-00da87ef3f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-w-[165px] items-center justify-center text-base font-bold transition delay-75 bg-white rounded-md text-cerulean-600 py-3 px-6 hover:bg-cerulean-100 hover:ring-cerulean-600</value>
      <webElementGuid>53d2c000-2572-4c3c-abe7-2929b7b2ec75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Program</value>
      <webElementGuid>f5ca8b78-55f2-4bbe-96b5-78094f60a886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;mx-auto pb-10 lg:pb-[108px] bg-opacity-50 mb-5&quot;]/div[@class=&quot;h-auto mx-auto&quot;]/div[@class=&quot;relative px-8 lg:px-[108px] pt-[138px] pb-6 sm:pb-[60px] lg:pt-[186px]&quot;]/div[@class=&quot;flex flex-col gap-[60px]&quot;]/div[@class=&quot;flex flex-col gap-5&quot;]/button[@class=&quot;max-w-[165px] items-center justify-center text-base font-bold transition delay-75 bg-white rounded-md text-cerulean-600 py-3 px-6 hover:bg-cerulean-100 hover:ring-cerulean-600&quot;]</value>
      <webElementGuid>44d29c8a-c0c0-40f6-94fd-bd6ff07f91f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/button</value>
      <webElementGuid>8c9e2dc2-dedf-43b5-92f3-d2576b1ce2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='with Metrodata Academy'])[1]/following::button[1]</value>
      <webElementGuid>8522aca0-7483-4c6e-b9af-38130aeaffde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelatih &amp; Sertifikat TI'])[1]/preceding::button[1]</value>
      <webElementGuid>b63c6264-1b4e-4943-873f-b3bbf31ed76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>e41d1762-7221-4aaf-8a46-c6ef94558b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@href = '#section-lihat-program' and (text() = 'Lihat Program' or . = 'Lihat Program')]</value>
      <webElementGuid>6141166d-de04-41e7-9866-b9c20037a4c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
