<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Metrodata Academy_w-9 h-9 lgw-10 lgh_1e0ff3</name>
   <tag></tag>
   <elementGuidId>2d6df34b-0d48-443e-aad4-03e0370193e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[4]/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6bb526db-4b9d-4db1-916c-fd8a12bf9560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-9 h-9 lg:w-10 lg:h-10 flex items-center justify-center relative bg-[#EFEFEF] rounded-full font-semibold text-white</value>
      <webElementGuid>b3c2a96f-2341-4422-9be7-00dc3b9a80f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;p-8 lg:py-24 xl:px-[108px]&quot;]/div[@class=&quot;flex flex-col items-center justify-center gap-5 mx-auto max-w-7xl&quot;]/div[@class=&quot;flex justify-between w-full&quot;]/div[@class=&quot;relative flex flex-col justify-center items-center w-full before:bg-[#EFEFEF] before:absolute before:-z-10 before:w-full before:h-[3px] before:right-2/4 before:top-1/3 before:-translate-y-2/4 false&quot;]/button[@class=&quot;w-9 h-9 lg:w-10 lg:h-10 flex items-center justify-center relative bg-[#EFEFEF] rounded-full font-semibold text-white&quot;]</value>
      <webElementGuid>c76cfde2-c3da-4fc4-92cb-c107566e58ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[4]/div/div/div[2]/button</value>
      <webElementGuid>1cf16565-e447-44e9-b49e-b4c0027234c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>21fa816c-174d-4953-8acb-dbd7fd4f97b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[4]/div/div/div[3]/button</value>
      <webElementGuid>b8c235f4-670a-4144-a8a7-96acb0ebce76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>9b1af8c1-140a-4183-a75b-8f1c7078b382</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
