<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Metrodata Academy_w-9 h-9 lgw-10 lgh_1e0ff3</name>
   <tag></tag>
   <elementGuidId>2d6df34b-0d48-443e-aad4-03e0370193e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[4]/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3406698-9caa-4db8-aa83-83e663670177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-9 h-9 lg:w-10 lg:h-10 flex items-center justify-center relative bg-[#EFEFEF] rounded-full font-semibold text-white</value>
      <webElementGuid>7b793673-cc21-40e0-b29d-525c800ec984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;p-8 lg:py-24 xl:px-[108px]&quot;]/div[@class=&quot;flex flex-col items-center justify-center gap-5 mx-auto max-w-7xl&quot;]/div[@class=&quot;flex justify-between w-full&quot;]/div[@class=&quot;relative flex flex-col justify-center items-center w-full before:bg-[#EFEFEF] before:absolute before:-z-10 before:w-full before:h-[3px] before:right-2/4 before:top-1/3 before:-translate-y-2/4 false&quot;]/button[@class=&quot;w-9 h-9 lg:w-10 lg:h-10 flex items-center justify-center relative bg-[#EFEFEF] rounded-full font-semibold text-white&quot;]</value>
      <webElementGuid>679e7431-a51b-4fed-bb9b-577b25fbba3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[4]/div/div/div[2]/button</value>
      <webElementGuid>81bc7927-9176-4b9d-82b7-6a352ceb923f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>a489554b-22d2-46fa-852a-438b32b7238e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[4]/div/div/div[3]/button</value>
      <webElementGuid>be5d746b-6013-4287-936c-cd6d80a3e942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>c1528e24-5597-4418-840b-99b10b20f8bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
