<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Acara di Metrodata MengajarCompTIA10 Ju_e9fc5c</name>
   <tag></tag>
   <elementGuidId>823e3d4e-b4a3-464e-9a23-ff14b96f68d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4196de2-8747-492f-adf3-0db2389810ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-auto px-9 py-8 lg:py-24 lg:px-[108px] bg-blue-50</value>
      <webElementGuid>e30db454-64bb-4632-8102-174d33a6b983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acara di Metrodata MengajarCompTIA10 June 2024OnlineProfessionalDaftar SekarangEdufair 202419 June 2024ClassroomProfessionalDaftar SekarangRed Hat - Openshift Administration01 July 2024OnlineProfessionalDaftar SekarangLihat semua kegiatan</value>
      <webElementGuid>1fd47efe-2948-412f-84bc-b9fc5a51d294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;w-full h-auto px-9 py-8 lg:py-24 lg:px-[108px] bg-blue-50&quot;]</value>
      <webElementGuid>5bb7e32f-1439-458d-903b-99397d45497a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]</value>
      <webElementGuid>b6e1888a-39e2-4587-9fe7-9ebdd64e3b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diisi dan didukung oleh semua Profesional IT di Metrodata'])[1]/following::div[1]</value>
      <webElementGuid>5cf70531-8d17-41a7-8696-5cda0eccbed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrodata Mengajar'])[2]/following::div[4]</value>
      <webElementGuid>9ca2aef6-8fc9-4039-881f-48a15dabce26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]</value>
      <webElementGuid>9c48e6e8-bf79-457c-bada-d00455f125d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Acara di Metrodata MengajarCompTIA10 June 2024OnlineProfessionalDaftar SekarangEdufair 202419 June 2024ClassroomProfessionalDaftar SekarangRed Hat - Openshift Administration01 July 2024OnlineProfessionalDaftar SekarangLihat semua kegiatan' or . = 'Acara di Metrodata MengajarCompTIA10 June 2024OnlineProfessionalDaftar SekarangEdufair 202419 June 2024ClassroomProfessionalDaftar SekarangRed Hat - Openshift Administration01 July 2024OnlineProfessionalDaftar SekarangLihat semua kegiatan')]</value>
      <webElementGuid>0954f6bb-afef-47d2-bf85-22abf034fd7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
