<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dapatkan penawaran menarik dan berita t_af1909</name>
   <tag></tag>
   <elementGuidId>de6e3993-4e10-415c-9762-76c6c4ae6c08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/footer/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>68de226d-6537-42d3-b753-3d533422801a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-4 px-4 sm:pr-3 bg-[#F9FAFB] sm:mt-20 lg:mt-24 lg:flex lg:items-center lg:justify-between lg:gap-x-3</value>
      <webElementGuid>c70bdb4b-0e16-4735-90d6-45429f9d07bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dapatkan penawaran menarik dan berita terbaruEmail addressSubscribe</value>
      <webElementGuid>dbd71dfc-04d6-4b53-8f32-a189caf4b968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/footer[@class=&quot;bg-cerulean-50&quot;]/div[@class=&quot;px-8 lg:px-[108px]&quot;]/div[@class=&quot;pt-8 mt-16 sm:pt-0 sm:mt-0&quot;]/div[@class=&quot;px-0 xl:px-32&quot;]/div[@class=&quot;py-4 px-4 sm:pr-3 bg-[#F9FAFB] sm:mt-20 lg:mt-24 lg:flex lg:items-center lg:justify-between lg:gap-x-3&quot;]</value>
      <webElementGuid>32500b4c-4443-4fc2-8ec4-f58ceb7f08ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/footer/div/div[2]/div/div</value>
      <webElementGuid>51c45d10-94e5-467e-a25c-fd0d4d17b102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support: contact@mii.co.id'])[1]/following::div[3]</value>
      <webElementGuid>a545e5c3-820f-4bfb-8873-5086fa071092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office: +62 811 19 500900'])[1]/following::div[3]</value>
      <webElementGuid>ecb542c3-0cff-4c78-9fe1-a0b61c471956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[2]/div/div</value>
      <webElementGuid>fd47fc19-0547-489b-8aeb-a3194ba0c912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dapatkan penawaran menarik dan berita terbaruEmail addressSubscribe' or . = 'Dapatkan penawaran menarik dan berita terbaruEmail addressSubscribe')]</value>
      <webElementGuid>25e572c4-1d43-4321-a73c-4104c776eebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
