<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nikmati keuntunganbersama Metrodata Aca_8f9d17</name>
   <tag></tag>
   <elementGuidId>24bf1431-ca7e-4a72-8498-168656da19a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4128db8a-081b-4123-a5fe-850d206231eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white p-8 lg:pb-[96px] lg:px-[96px] lg:pt-[76px]</value>
      <webElementGuid>72a5adb6-3603-4cb7-8c35-e90a3df19d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nikmati keuntunganbersama Metrodata Academy01Solusi Lengkap EdukasiMetrodata Academy memberi beragam pilihan kebutuhan edukasi, mulai dari pelatihan dan sertifikasi profesional, program akademi kampus, penempatan kerja, magang, sampai dengan berbagai ilmu terkait Teknologi Informasi.02Pengajar HandalKami memiliki mentor atau pengajar yang sudah berpengalaman dan ahli di bidangnya untuk Anda.03Dapat Belajar di mana punMetrodata Academy dapat diakses di mana saja sehingga Anda dapat belajar dengan mentor handal di mana pun.</value>
      <webElementGuid>58068b28-ed0b-47ac-adb0-94db280d34b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;bg-white p-8 lg:pb-[96px] lg:px-[96px] lg:pt-[76px]&quot;]</value>
      <webElementGuid>3e67619a-c76a-4241-82df-f6d4f24d2bbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[4]</value>
      <webElementGuid>bb8cacc8-42a8-4bac-a623-1b27a11b3ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[4]/following::div[1]</value>
      <webElementGuid>8ad138ef-47a3-4fcb-a830-db66e3f4df4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[3]/following::div[6]</value>
      <webElementGuid>3db37189-258d-4f91-a081-369256439c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[4]</value>
      <webElementGuid>502af02c-89ee-4eb3-84c9-46902679d1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nikmati keuntunganbersama Metrodata Academy01Solusi Lengkap EdukasiMetrodata Academy memberi beragam pilihan kebutuhan edukasi, mulai dari pelatihan dan sertifikasi profesional, program akademi kampus, penempatan kerja, magang, sampai dengan berbagai ilmu terkait Teknologi Informasi.02Pengajar HandalKami memiliki mentor atau pengajar yang sudah berpengalaman dan ahli di bidangnya untuk Anda.03Dapat Belajar di mana punMetrodata Academy dapat diakses di mana saja sehingga Anda dapat belajar dengan mentor handal di mana pun.' or . = 'Nikmati keuntunganbersama Metrodata Academy01Solusi Lengkap EdukasiMetrodata Academy memberi beragam pilihan kebutuhan edukasi, mulai dari pelatihan dan sertifikasi profesional, program akademi kampus, penempatan kerja, magang, sampai dengan berbagai ilmu terkait Teknologi Informasi.02Pengajar HandalKami memiliki mentor atau pengajar yang sudah berpengalaman dan ahli di bidangnya untuk Anda.03Dapat Belajar di mana punMetrodata Academy dapat diakses di mana saja sehingga Anda dapat belajar dengan mentor handal di mana pun.')]</value>
      <webElementGuid>c051b2c3-c5b0-4620-a2b6-bdbb5c1d8119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
