<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Detail</name>
   <tag></tag>
   <elementGuidId>78951e98-1ca2-47b9-84da-7334e94910d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='section-lihat-program']/div/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-start.w-full.mt-auto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76ebad5f-1418-4bbe-a220-3443f321d14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-start w-full mt-auto</value>
      <webElementGuid>f61c47ee-234c-4245-a747-a1fd6d3106d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>9a6105f3-1fa8-4f6c-8c8a-883071f2acad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-lihat-program&quot;)/div[@class=&quot;scroll-smooth&quot;]/div[@class=&quot;p-8 bg-[#F4F7FF] lg:py-24 lg:px-[108px]&quot;]/div[@class=&quot;flex flex-col items-center justify-center w-full mx-auto&quot;]/div[@class=&quot;grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 md:place-content-center items-start gap-2&quot;]/div[@class=&quot;flex flex-col p-6 items-start gap-3 rounded-lg bg-white w-full h-full lg:max-w-[300px]&quot;]/div[@class=&quot;flex items-start w-full mt-auto&quot;]</value>
      <webElementGuid>1673ed98-76a7-44fa-9dba-b5acef9296eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section-lihat-program']/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>200009f8-0d1f-4aac-9881-a99076ea1a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bergabung dengan program unggulan kami'])[1]/following::div[6]</value>
      <webElementGuid>e0a21a4c-18e5-4e9b-9eca-fa414de5b6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[2]/preceding::div[4]</value>
      <webElementGuid>05e6178c-4410-49ce-be38-9b79ea85bca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>7cc2adbf-f034-496c-8f4e-cff5c991d28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>a7bc083a-6999-40a0-841e-c1029f1fbbaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
