<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Metrodata AcademySetelah lebih dari 40 _93b162</name>
   <tag></tag>
   <elementGuidId>c6058a35-e611-4180-8af1-a167997efe42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fe356195-a8ac-459b-b37a-cd2c33a9d1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col items-center gap-8 mx-auto py-8 px-9 lg:py-24 lg:px-[108px]</value>
      <webElementGuid>4cd84c8e-4df9-4efc-972c-b6941669a33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Metrodata AcademySetelah lebih dari 40 tahun menjadi bagian dari perkembangan teknologi di Indonesia, Metrodata, ikut mengembangkan potensi talenta digital Indonesia melalui Metrodata Academy yang berdiri sejak tahun 2020.</value>
      <webElementGuid>e6861d1d-f5a2-4561-9e20-5a9a01858fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;flex flex-col items-center gap-8 mx-auto py-8 px-9 lg:py-24 lg:px-[108px]&quot;]</value>
      <webElementGuid>d61404dc-cbac-4d80-93fc-fd120fa83347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]</value>
      <webElementGuid>c8b2acf6-7b42-461c-beaa-fad7d7031b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::div[6]</value>
      <webElementGuid>a0209b2a-ea19-40b1-9993-af9e59d802f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footer'])[1]/preceding::div[31]</value>
      <webElementGuid>5a4d3b94-0976-4fde-ad0c-c1ab4554935a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]</value>
      <webElementGuid>1d72f7fc-a6b3-438b-a27b-d8a7c188a1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Metrodata AcademySetelah lebih dari 40 tahun menjadi bagian dari perkembangan teknologi di Indonesia, Metrodata, ikut mengembangkan potensi talenta digital Indonesia melalui Metrodata Academy yang berdiri sejak tahun 2020.' or . = 'Metrodata AcademySetelah lebih dari 40 tahun menjadi bagian dari perkembangan teknologi di Indonesia, Metrodata, ikut mengembangkan potensi talenta digital Indonesia melalui Metrodata Academy yang berdiri sejak tahun 2020.')]</value>
      <webElementGuid>b08c2635-652d-4f63-a0b8-c92ac4fb0ba3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
