<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Magang Bersertifikat Kampus Merdeka Pro_fec729</name>
   <tag></tag>
   <elementGuidId>d69139d7-3988-494d-9f87-f48e392caddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>71127523-307a-4f98-9ea4-165db0d675bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col-reverse xl:flex-row p-8 lg:px-[108px] lg:py-24 gap-5 lg:gap-20</value>
      <webElementGuid>9a0ed1c8-db2d-445a-9d8c-5064758ed318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Magang Bersertifikat Kampus Merdeka Program kerja sama Metrodata Academy dan Kementerian Pendidikan, Budaya, Riset, dan Teknologi Republik Indonesia untuk talenta digital yang ingin mengeksplor kesempatan baru di Technical, Business Development, Human Resources, Business Support, dan Digital Marketing.</value>
      <webElementGuid>326a4344-7e5b-4f33-9707-1bdf5f5e8615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;flex flex-col-reverse xl:flex-row p-8 lg:px-[108px] lg:py-24 gap-5 lg:gap-20&quot;]</value>
      <webElementGuid>3d3f9274-2764-4b96-b4f5-3155f99e0241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]</value>
      <webElementGuid>775fd24f-3656-49cf-ba33-9f14ebbbc231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrodata Internship'])[2]/following::div[1]</value>
      <webElementGuid>6dfb0f3d-9f01-4366-98a7-1d5c3aa7ea06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::div[7]</value>
      <webElementGuid>9fb4f96f-b1d5-4c21-99e2-4dec23ee69ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testimoni Metrodata Internship'])[1]/preceding::div[2]</value>
      <webElementGuid>5e1fcd7d-dbc3-4a8b-94cd-eab7ef239024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]</value>
      <webElementGuid>783c7922-abd8-45ef-9678-0a057944d67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Magang Bersertifikat Kampus Merdeka Program kerja sama Metrodata Academy dan Kementerian Pendidikan, Budaya, Riset, dan Teknologi Republik Indonesia untuk talenta digital yang ingin mengeksplor kesempatan baru di Technical, Business Development, Human Resources, Business Support, dan Digital Marketing.' or . = 'Magang Bersertifikat Kampus Merdeka Program kerja sama Metrodata Academy dan Kementerian Pendidikan, Budaya, Riset, dan Teknologi Republik Indonesia untuk talenta digital yang ingin mengeksplor kesempatan baru di Technical, Business Development, Human Resources, Business Support, dan Digital Marketing.')]</value>
      <webElementGuid>48c74ca2-c021-43fc-a5c5-366d952aeba5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
