<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Latar Belakang Metrodata AcademyMetroda_9f4957</name>
   <tag></tag>
   <elementGuidId>e58cbf77-ca9a-4331-b37a-96a1f8590236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-col.gap-10.justify-center.items-center.max-w-7xl.mx-auto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3e7f3348-103f-4f81-8d49-1a6c3e751f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col gap-10 justify-center items-center max-w-7xl mx-auto</value>
      <webElementGuid>d79b8ac2-5bae-42bb-bea2-167be6c85db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Latar Belakang Metrodata AcademyMetrodata Academy dibangun untuk ikut mencerdaskan kehidupan bangsa oleh:PT Metrodata Electronics TbkPT Metrodata Electronics Tbk (Perseroan) adalah perusahaan publik yang sahamnya tercatat di PT Bursa Efek Indonesia sejak tahun 1990 (IDX:MTDL) dan merupakan perusahaan Teknologi Informasi dan Komunikasi (TIK) terdepan di Indonesia yang telah bermitra dengan perusahaan-perusahaan TI kelas dunia sejak tahun 1975. Perseroan dikenal memiliki portofolio yang komprehensif dalam bidang distribusi perangkat keras dan peranti lunak TIK. Perseroan pada saat ini memiliki tiga bisnis utama yaitu Bisnis Distribusi yang menangani bidang usaha distribusi kepada dealer, perusahaan solusi TIK, dan e-commerce, Bisnis Solusi yang menyediakan solusi lengkap TIK mulai dari perancangan, implementasi, IT Managed Services, konsultasi dan pelatihan, Bisnis Konsultasi yang menawarkan solusi bisnis inovatif untuk transformasi bisnis.PT Mitra Integrasi Informatika (MII)PT Mitra Integrasi Informatika (MII) merupakan garda terdepan bisnis solusi teknologi informasi komunikasi kelompok usaha METRODATA. Sejak didirikan tanggal 1 Maret 1996, MII secara konsisten memfokuskan pelayanannya bagi pelanggan korporasi pasar enterprise di berbagai sektor industri maupun pasar UKM. MII telah berpartner dengan partner solusi TIK kelas dunia di area hardware, software dan services. MII menyediakan solusi kepada pelanggan mulai dari tahap desain dan blue print, konsultasi, implementasi, dukungan, pemeliharaan, managed services dan pelatihan.PT Sinergi Transformasi Digital (SINERGI)PT Sinergi Transformasi Digital (“SINERGI”) adalah bagian dari Indonesia. Sebagai perusahaan Teknologi Informasi, SINERGI terpanggil untuk berperan serta dalam pembangunan nasional dengan mengadopsi teknologi terbaik di dunia. SINERGI hadir dalam memberikan solusi, memiliki peran dan tanggung jawab, serta dinamika dalam keberagaman.</value>
      <webElementGuid>04fc8d77-4a8a-43bf-9ba2-d359bb2d4118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;px-8 lg:px-[108px]&quot;]/div[@class=&quot;flex flex-col gap-10 justify-center items-center max-w-7xl mx-auto&quot;]</value>
      <webElementGuid>64502111-952c-4463-bb0b-e95f076a2c00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div</value>
      <webElementGuid>4863fb52-b1b6-46b1-9d55-01bade451ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrodata Academy'])[3]/following::div[4]</value>
      <webElementGuid>cb7c5381-f22c-4fbc-a77e-9d7bbdf52aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footer'])[1]/preceding::div[26]</value>
      <webElementGuid>cdf775a8-1bc5-4501-afb0-67bd2cbb7657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/preceding::div[27]</value>
      <webElementGuid>a8a8c510-bd55-4f54-b5f6-3ccaaebed1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div</value>
      <webElementGuid>bcab0020-f735-4363-8083-a5efe6423a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Latar Belakang Metrodata AcademyMetrodata Academy dibangun untuk ikut mencerdaskan kehidupan bangsa oleh:PT Metrodata Electronics TbkPT Metrodata Electronics Tbk (Perseroan) adalah perusahaan publik yang sahamnya tercatat di PT Bursa Efek Indonesia sejak tahun 1990 (IDX:MTDL) dan merupakan perusahaan Teknologi Informasi dan Komunikasi (TIK) terdepan di Indonesia yang telah bermitra dengan perusahaan-perusahaan TI kelas dunia sejak tahun 1975. Perseroan dikenal memiliki portofolio yang komprehensif dalam bidang distribusi perangkat keras dan peranti lunak TIK. Perseroan pada saat ini memiliki tiga bisnis utama yaitu Bisnis Distribusi yang menangani bidang usaha distribusi kepada dealer, perusahaan solusi TIK, dan e-commerce, Bisnis Solusi yang menyediakan solusi lengkap TIK mulai dari perancangan, implementasi, IT Managed Services, konsultasi dan pelatihan, Bisnis Konsultasi yang menawarkan solusi bisnis inovatif untuk transformasi bisnis.PT Mitra Integrasi Informatika (MII)PT Mitra Integrasi Informatika (MII) merupakan garda terdepan bisnis solusi teknologi informasi komunikasi kelompok usaha METRODATA. Sejak didirikan tanggal 1 Maret 1996, MII secara konsisten memfokuskan pelayanannya bagi pelanggan korporasi pasar enterprise di berbagai sektor industri maupun pasar UKM. MII telah berpartner dengan partner solusi TIK kelas dunia di area hardware, software dan services. MII menyediakan solusi kepada pelanggan mulai dari tahap desain dan blue print, konsultasi, implementasi, dukungan, pemeliharaan, managed services dan pelatihan.PT Sinergi Transformasi Digital (SINERGI)PT Sinergi Transformasi Digital (“SINERGI”) adalah bagian dari Indonesia. Sebagai perusahaan Teknologi Informasi, SINERGI terpanggil untuk berperan serta dalam pembangunan nasional dengan mengadopsi teknologi terbaik di dunia. SINERGI hadir dalam memberikan solusi, memiliki peran dan tanggung jawab, serta dinamika dalam keberagaman.' or . = 'Latar Belakang Metrodata AcademyMetrodata Academy dibangun untuk ikut mencerdaskan kehidupan bangsa oleh:PT Metrodata Electronics TbkPT Metrodata Electronics Tbk (Perseroan) adalah perusahaan publik yang sahamnya tercatat di PT Bursa Efek Indonesia sejak tahun 1990 (IDX:MTDL) dan merupakan perusahaan Teknologi Informasi dan Komunikasi (TIK) terdepan di Indonesia yang telah bermitra dengan perusahaan-perusahaan TI kelas dunia sejak tahun 1975. Perseroan dikenal memiliki portofolio yang komprehensif dalam bidang distribusi perangkat keras dan peranti lunak TIK. Perseroan pada saat ini memiliki tiga bisnis utama yaitu Bisnis Distribusi yang menangani bidang usaha distribusi kepada dealer, perusahaan solusi TIK, dan e-commerce, Bisnis Solusi yang menyediakan solusi lengkap TIK mulai dari perancangan, implementasi, IT Managed Services, konsultasi dan pelatihan, Bisnis Konsultasi yang menawarkan solusi bisnis inovatif untuk transformasi bisnis.PT Mitra Integrasi Informatika (MII)PT Mitra Integrasi Informatika (MII) merupakan garda terdepan bisnis solusi teknologi informasi komunikasi kelompok usaha METRODATA. Sejak didirikan tanggal 1 Maret 1996, MII secara konsisten memfokuskan pelayanannya bagi pelanggan korporasi pasar enterprise di berbagai sektor industri maupun pasar UKM. MII telah berpartner dengan partner solusi TIK kelas dunia di area hardware, software dan services. MII menyediakan solusi kepada pelanggan mulai dari tahap desain dan blue print, konsultasi, implementasi, dukungan, pemeliharaan, managed services dan pelatihan.PT Sinergi Transformasi Digital (SINERGI)PT Sinergi Transformasi Digital (“SINERGI”) adalah bagian dari Indonesia. Sebagai perusahaan Teknologi Informasi, SINERGI terpanggil untuk berperan serta dalam pembangunan nasional dengan mengadopsi teknologi terbaik di dunia. SINERGI hadir dalam memberikan solusi, memiliki peran dan tanggung jawab, serta dinamika dalam keberagaman.')]</value>
      <webElementGuid>29288f63-ae7a-41cf-ac7c-bbe8620051e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
