<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Apa kata mereka tentang program kamiInt_94d5ba</name>
   <tag></tag>
   <elementGuidId>6c9802c2-a2be-4bd2-9815-9229a318a564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2c0d2614-f6f4-4713-b416-0aab454a7ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-[#FFF] rounded-lg p-8 md:pt-[90px] md:pb-10 lg:px-[108px] flex flex-col justify-center items-center</value>
      <webElementGuid>7f2cf65b-04e4-445f-a18a-bf6cd6881e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apa kata mereka tentang program kami?&quot;Internship di Metrodata memberikan pengalaman praktis dan ilmu yang berharga. Terampil dalam pemrograman dan manajemen proyek berkat bimbingan profesional yang luar biasa!&quot;Marvel KrentMahasiswaInternship&quot;Internship di Metrodata Academy melibatkan saya dalam real-project proses bisnis perusahaan khususnya Mitra Integrasi Informatika, serta memperluas pengetahuan praktis dan keterampilan kolaborasi&quot;Nathanael Abel AriantoiOS Developer Intern at Apple Developer AcademyInternship&quot;Mengikuti internship di Metrodata sangat berkesan dan menambah insight saya untuk bekerja di industri IT&quot;Debora Gabriella AmabelMahasiswaInternship&quot;Overall materi yang disampaikan mencukupi kebutuhan dan penyampaian materi oleh trainer cukup jelas&quot;Asep WijayaBusiness Intelligence LeadTraining&quot;Metrodata Academy sangat membantu dalam memahami modul yang sedang dipelajari. Pengajarnya berpengalaman dan selama training komunikasi 2 arah terjalin.&quot;Laurensius LubisKaryawanTraining&quot;Materi training update terhadap kebutuhan industri terkini, cocok untuk persiapan sebelum masuk ke industri IT.&quot;Darwin ManurungApplication DeveloperIT Camp</value>
      <webElementGuid>0ea87aa2-bc41-44eb-8c61-47315800601d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;bg-[#FFF] rounded-lg p-8 md:pt-[90px] md:pb-10 lg:px-[108px] flex flex-col justify-center items-center&quot;]</value>
      <webElementGuid>0dd329da-f8c2-458b-8d6d-214e5475d717</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[6]</value>
      <webElementGuid>ecfcd61d-19b2-4d7e-975c-374b6870a9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baca Selengkapnya'])[3]/following::div[1]</value>
      <webElementGuid>d9a6ee3f-5c1e-4a0f-a66d-69231df2bdd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrodata Menghadiri Undangan Penandatanganan Perjanjian Kerja Sama (PKS) Program MSIB Batch 6'])[1]/following::div[1]</value>
      <webElementGuid>80fdc7ec-6cd7-4c73-bbd7-a386d73f2649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>80adcee8-2216-449f-9dfa-eaee75338b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Apa kata mereka tentang program kami?&quot;Internship di Metrodata memberikan pengalaman praktis dan ilmu yang berharga. Terampil dalam pemrograman dan manajemen proyek berkat bimbingan profesional yang luar biasa!&quot;Marvel KrentMahasiswaInternship&quot;Internship di Metrodata Academy melibatkan saya dalam real-project proses bisnis perusahaan khususnya Mitra Integrasi Informatika, serta memperluas pengetahuan praktis dan keterampilan kolaborasi&quot;Nathanael Abel AriantoiOS Developer Intern at Apple Developer AcademyInternship&quot;Mengikuti internship di Metrodata sangat berkesan dan menambah insight saya untuk bekerja di industri IT&quot;Debora Gabriella AmabelMahasiswaInternship&quot;Overall materi yang disampaikan mencukupi kebutuhan dan penyampaian materi oleh trainer cukup jelas&quot;Asep WijayaBusiness Intelligence LeadTraining&quot;Metrodata Academy sangat membantu dalam memahami modul yang sedang dipelajari. Pengajarnya berpengalaman dan selama training komunikasi 2 arah terjalin.&quot;Laurensius LubisKaryawanTraining&quot;Materi training update terhadap kebutuhan industri terkini, cocok untuk persiapan sebelum masuk ke industri IT.&quot;Darwin ManurungApplication DeveloperIT Camp' or . = 'Apa kata mereka tentang program kami?&quot;Internship di Metrodata memberikan pengalaman praktis dan ilmu yang berharga. Terampil dalam pemrograman dan manajemen proyek berkat bimbingan profesional yang luar biasa!&quot;Marvel KrentMahasiswaInternship&quot;Internship di Metrodata Academy melibatkan saya dalam real-project proses bisnis perusahaan khususnya Mitra Integrasi Informatika, serta memperluas pengetahuan praktis dan keterampilan kolaborasi&quot;Nathanael Abel AriantoiOS Developer Intern at Apple Developer AcademyInternship&quot;Mengikuti internship di Metrodata sangat berkesan dan menambah insight saya untuk bekerja di industri IT&quot;Debora Gabriella AmabelMahasiswaInternship&quot;Overall materi yang disampaikan mencukupi kebutuhan dan penyampaian materi oleh trainer cukup jelas&quot;Asep WijayaBusiness Intelligence LeadTraining&quot;Metrodata Academy sangat membantu dalam memahami modul yang sedang dipelajari. Pengajarnya berpengalaman dan selama training komunikasi 2 arah terjalin.&quot;Laurensius LubisKaryawanTraining&quot;Materi training update terhadap kebutuhan industri terkini, cocok untuk persiapan sebelum masuk ke industri IT.&quot;Darwin ManurungApplication DeveloperIT Camp')]</value>
      <webElementGuid>4b570329-b1df-493e-ac6f-36db0c2a3d54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
