<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bergabung dengan program unggulan kamiM_bb07e7</name>
   <tag></tag>
   <elementGuidId>f44cd971-0bde-461c-98e2-7f6e5fd1af15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='section-lihat-program']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6dd89f9e-0949-4690-bf32-9807784d9984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-8 bg-[#F4F7FF] lg:py-24 lg:px-[108px]</value>
      <webElementGuid>2d82367e-c4bc-46d7-9795-1836f4a4a700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bergabung dengan program unggulan kamiMetrodata TrainingMenyediakan berbagai pelatihan bersertifikasi untuk publik yang dilakukan secara daring dan luringDetailMetrodata IT CampProgram belajar intensif bersama mentor berpengalaman melalui tahapan seleksi dan ujian untuk menghasilkan tenaga Teknologi Informasi profesionalDetailMetrodata InternshipMengembangkan keahlian dan pengalaman yang menghasilkan profesional di bidang teknologi informasi yang siap bekerjaDetailMetrodata MengajarProgram edukasi dan berbagi pengalaman secara gratis oleh tenaga ahli dan seluruh entitas Metrodata kepada para praktisi TI.Detail</value>
      <webElementGuid>362e2ac3-3446-4046-924f-35f15d060912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-lihat-program&quot;)/div[@class=&quot;scroll-smooth&quot;]/div[@class=&quot;p-8 bg-[#F4F7FF] lg:py-24 lg:px-[108px]&quot;]</value>
      <webElementGuid>c392bf5f-0047-47a0-aa8b-8da63a0f0056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section-lihat-program']/div/div</value>
      <webElementGuid>6fa9a16b-d4ea-4401-a80e-613915b06611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div</value>
      <webElementGuid>9e70f0b4-1006-4eb5-a777-202b5ae81d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bergabung dengan program unggulan kamiMetrodata TrainingMenyediakan berbagai pelatihan bersertifikasi untuk publik yang dilakukan secara daring dan luringDetailMetrodata IT CampProgram belajar intensif bersama mentor berpengalaman melalui tahapan seleksi dan ujian untuk menghasilkan tenaga Teknologi Informasi profesionalDetailMetrodata InternshipMengembangkan keahlian dan pengalaman yang menghasilkan profesional di bidang teknologi informasi yang siap bekerjaDetailMetrodata MengajarProgram edukasi dan berbagi pengalaman secara gratis oleh tenaga ahli dan seluruh entitas Metrodata kepada para praktisi TI.Detail' or . = 'Bergabung dengan program unggulan kamiMetrodata TrainingMenyediakan berbagai pelatihan bersertifikasi untuk publik yang dilakukan secara daring dan luringDetailMetrodata IT CampProgram belajar intensif bersama mentor berpengalaman melalui tahapan seleksi dan ujian untuk menghasilkan tenaga Teknologi Informasi profesionalDetailMetrodata InternshipMengembangkan keahlian dan pengalaman yang menghasilkan profesional di bidang teknologi informasi yang siap bekerjaDetailMetrodata MengajarProgram edukasi dan berbagi pengalaman secara gratis oleh tenaga ahli dan seluruh entitas Metrodata kepada para praktisi TI.Detail')]</value>
      <webElementGuid>9243b1bb-645c-44b4-b784-a998d84b3b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
