<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Keuntungan yang kamu dapatkan di Metrod_8c51c9</name>
   <tag></tag>
   <elementGuidId>8501b81c-0149-43ae-b580-82122702cee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9eab7c6-d000-4f84-bbed-c712fcec18bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-auto bg-white py-8 px-9 lg:py-24 lg:px-[108px]</value>
      <webElementGuid>deb6b1c1-856e-46d9-8148-58f03a31b0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keuntungan yang kamu dapatkan di Metrodata InternshipMendukung program Kampus Merdeka dengan magang berbasis proyek nyata untuk mahasiswa.PelatihanPeserta magang diberikan pelatihan dalam rangka beradaptasi dengan dunia industri.PengalamanPeserta magang mendapatkan pengalaman mengerjakan project yang bisa juga diambil menjadi topik skripsi.KarirPeserta magang berkesempatan diangkat menjadi seorang karyawan walaupun masih dalam masa magang.AllowanceAllowance atau uang Saku Diberikan bagi peserta magang yang ditempatkan di kantor, Jakarta, maupun bagi peserta yang mengerjakan project in site.</value>
      <webElementGuid>313d82d2-2311-44e3-9f6c-abc1e72f2633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;w-full h-auto bg-white py-8 px-9 lg:py-24 lg:px-[108px]&quot;]</value>
      <webElementGuid>5e7d781d-ba63-498d-aa97-4646be4f2784</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[5]</value>
      <webElementGuid>0e17622e-3708-4e2d-b97c-a76412c2ae07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrodata Internship telah bekerja sama dengan Universitas di seluruh Indonesia'])[1]/following::div[89]</value>
      <webElementGuid>50f81088-9375-4fc9-8220-4dcd09450e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bergabung sekarang'])[1]/following::div[91]</value>
      <webElementGuid>11c644e0-9b06-474e-9c53-8289bf37d352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>a1fa0013-9f2b-49f4-9544-4c2cbee1e90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Keuntungan yang kamu dapatkan di Metrodata InternshipMendukung program Kampus Merdeka dengan magang berbasis proyek nyata untuk mahasiswa.PelatihanPeserta magang diberikan pelatihan dalam rangka beradaptasi dengan dunia industri.PengalamanPeserta magang mendapatkan pengalaman mengerjakan project yang bisa juga diambil menjadi topik skripsi.KarirPeserta magang berkesempatan diangkat menjadi seorang karyawan walaupun masih dalam masa magang.AllowanceAllowance atau uang Saku Diberikan bagi peserta magang yang ditempatkan di kantor, Jakarta, maupun bagi peserta yang mengerjakan project in site.' or . = 'Keuntungan yang kamu dapatkan di Metrodata InternshipMendukung program Kampus Merdeka dengan magang berbasis proyek nyata untuk mahasiswa.PelatihanPeserta magang diberikan pelatihan dalam rangka beradaptasi dengan dunia industri.PengalamanPeserta magang mendapatkan pengalaman mengerjakan project yang bisa juga diambil menjadi topik skripsi.KarirPeserta magang berkesempatan diangkat menjadi seorang karyawan walaupun masih dalam masa magang.AllowanceAllowance atau uang Saku Diberikan bagi peserta magang yang ditempatkan di kantor, Jakarta, maupun bagi peserta yang mengerjakan project in site.')]</value>
      <webElementGuid>dcf6a8fd-6d0b-4a91-ac4e-2acdaa46c866</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
