<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Metrodata Academy_bg-FEEBEB rounded-md p-4</name>
   <tag></tag>
   <elementGuidId>5b938ca3-e5b6-47b1-a9dc-c50b2c522fdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e068c393-e244-456c-81f1-9b5460bc169f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white mx-auto p-12 xxs:pt-6 xxs:px-6 xxs:pb-3 md:px-16 max-[300px]:p-6</value>
      <webElementGuid>58082576-735f-4b63-b9c8-4dcb73e011e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;bg-white mx-auto p-12 xxs:pt-6 xxs:px-6 xxs:pb-3 md:px-16 max-[300px]:p-6&quot;]</value>
      <webElementGuid>fe434661-845b-4d7b-9a21-2bc450b1de81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]</value>
      <webElementGuid>b126e100-02bf-46da-b259-34a2dafe988f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mahasiswa &amp; Fresh Graduate Bergabung'])[1]/following::div[1]</value>
      <webElementGuid>b44d2140-ed15-4c01-96bf-f06f6d47c664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jadwal Training dan Workshop Bersertifikasi yang Tersedia'])[1]/preceding::div[4]</value>
      <webElementGuid>acf14a0c-96ee-43cc-a61c-4a7c9afb1ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/preceding::div[5]</value>
      <webElementGuid>181ae362-1b6e-430e-94f9-aced24b46aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]</value>
      <webElementGuid>fc057477-ce51-4cf7-8614-bd9ca8d299a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[5]/div/div[3]/div</value>
      <webElementGuid>aaacd6c2-b68c-4d08-a41c-d85d66b0f040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrodata Academy'])[3]/following::div[28]</value>
      <webElementGuid>ea99d43e-aa81-48f0-b1e8-6bce00819002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footer'])[1]/preceding::div[2]</value>
      <webElementGuid>e1032004-2471-4910-9027-1b780ad0d9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/preceding::div[3]</value>
      <webElementGuid>b6f318fa-fc3c-4baf-b576-ae3cab1dcc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div</value>
      <webElementGuid>bef18a9a-a1d3-4b7d-b95a-a9abfc6cdc10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
