<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_May 2024Previous weekTodayNext weekO_848220</name>
   <tag></tag>
   <elementGuidId>9f521fb8-18af-4d27-a8c0-b399ac3c136a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>header.flex.bg-gray-50.items-center.justify-between.flex-none.px-6.py-4.border-b.border-gray-200</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div[3]/header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>10fedd45-d99f-4cc3-ba44-db69d4037d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex bg-gray-50 items-center justify-between flex-none px-6 py-4 border-b border-gray-200</value>
      <webElementGuid>f80df4b3-1368-4cf0-aaef-963fbca58c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>May 2024Previous weekTodayNext weekOpen menu</value>
      <webElementGuid>7c57b692-33b5-4969-8a90-4532d47fc361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;flex flex-col px-8 pb-8 lg:px-[108px]&quot;]/div[@class=&quot;flex flex-col h-full mx-auto border border-1 rounded-lg w-full mb-10&quot;]/header[@class=&quot;flex bg-gray-50 items-center justify-between flex-none px-6 py-4 border-b border-gray-200&quot;]</value>
      <webElementGuid>51141a70-95bd-4bbe-a134-90f91402ff71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div[3]/header</value>
      <webElementGuid>0b31db85-46e3-4dc1-b3a1-28b4464eabba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrodata Internship'])[2]/following::header[1]</value>
      <webElementGuid>a6c7962d-a976-4fd2-9fc8-7b1bb5c88304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrodata Mengajar'])[2]/following::header[1]</value>
      <webElementGuid>e9cd827e-19fb-4bcc-8b3b-a0a325324009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/header</value>
      <webElementGuid>6bb4f732-9ab9-47ab-8b7a-98176d131133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[(text() = 'May 2024Previous weekTodayNext weekOpen menu' or . = 'May 2024Previous weekTodayNext weekOpen menu')]</value>
      <webElementGuid>a0fe7666-a03b-4174-982e-90c6fdd2e9ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
