<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_May 2024Previous weekTodayNext weekO_848220</name>
   <tag></tag>
   <elementGuidId>9f521fb8-18af-4d27-a8c0-b399ac3c136a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div[3]/header</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>header.flex.bg-gray-50.items-center.justify-between.flex-none.px-6.py-4.border-b.border-gray-200</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>4fcb4703-eb88-4782-a89f-a7cfff6e1f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex bg-gray-50 items-center justify-between flex-none px-6 py-4 border-b border-gray-200</value>
      <webElementGuid>c5a22d4e-ee9c-499f-9c7d-e94a87dab54f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>May 2024Previous weekTodayNext weekOpen menu</value>
      <webElementGuid>74f892ab-67d5-4ef3-919a-186a430e1aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;flex flex-col px-8 pb-8 lg:px-[108px]&quot;]/div[@class=&quot;flex flex-col h-full mx-auto border border-1 rounded-lg w-full mb-10&quot;]/header[@class=&quot;flex bg-gray-50 items-center justify-between flex-none px-6 py-4 border-b border-gray-200&quot;]</value>
      <webElementGuid>e7dfaba0-6c34-4db5-ac3b-dbb5e832e26e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div[3]/header</value>
      <webElementGuid>a5624252-32b3-4979-9cac-45e0f949b95d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrodata Internship'])[2]/following::header[1]</value>
      <webElementGuid>090ca3a4-8056-4b22-bf89-fb234e74933f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrodata Mengajar'])[2]/following::header[1]</value>
      <webElementGuid>aaa25c5c-083c-49e1-8f5b-ae2cc8ca2c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/header</value>
      <webElementGuid>72a3dddc-0413-4d0e-b647-bc36441e2e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[(text() = 'May 2024Previous weekTodayNext weekOpen menu' or . = 'May 2024Previous weekTodayNext weekOpen menu')]</value>
      <webElementGuid>1838ea1a-155f-45f6-bcaf-959485a1c378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
