<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Daftar Sekarang_w-full  object-cover ob_f1bee0</name>
   <tag></tag>
   <elementGuidId>bc2bc84a-e9bb-4957-b53c-8713c382f5ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div/div/a[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>25104873-5369-42a6-8e63-fb5ce21760e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://metrodataacademy.s3.ap-southeast-1.amazonaws.com/webinar/webinar-132059.jpg</value>
      <webElementGuid>1e7b840c-cf00-4a7b-9401-f3bd7c15aac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Card Header Image</value>
      <webElementGuid>58f06e6d-c37e-4d0f-825e-31376931143d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full  object-cover object-center rounded-t-lg</value>
      <webElementGuid>5c00274f-30ec-4d0a-95f2-e5442f60735c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;w-full h-auto px-9 py-8 lg:py-24 lg:px-[108px] bg-blue-50&quot;]/div[@class=&quot;flex flex-col gap-10 mx-auto max-w-7xl&quot;]/div[@class=&quot;grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6&quot;]/a[@class=&quot;cur  sor-pointer&quot;]/div[@class=&quot;flex flex-col transition duration-500 ease-in-out bg-white border border-gray-200 rounded-lg shadow-md hover:bg-cerulean-50&quot;]/div[@class=&quot;rounded-lg h-full&quot;]/img[@class=&quot;w-full  object-cover object-center rounded-t-lg&quot;]</value>
      <webElementGuid>7eb7e728-0c9d-480f-bd7f-1bef6d519b97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div/a[2]/div/div/img</value>
      <webElementGuid>42f1ec5e-e8c9-4fbc-bc8d-b5dfe4c893cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Card Header Image'])[2]</value>
      <webElementGuid>c56a8301-ab29-42c8-8477-84b079900693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/div/img</value>
      <webElementGuid>002e9483-d085-4aa0-970b-777874d87c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://metrodataacademy.s3.ap-southeast-1.amazonaws.com/webinar/webinar-132059.jpg' and @alt = 'Card Header Image']</value>
      <webElementGuid>dd8f5c1f-9524-4bdb-818b-ae30cc19ed59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
