<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Email sudah terdaftar</name>
   <tag></tag>
   <elementGuidId>50a0bd3a-1ce4-41b7-a71e-1c115b3bb421</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/ol/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>84f3ba18-13b2-408b-94d7-dbd1dde88dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>b0113721-d9f1-4859-ae44-ddb672f0fce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>35ce0493-3d71-4e23-9b34-086356020a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>553ab3da-d404-4b16-9428-94bc522769e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>167dea77-276c-4be3-9aae-09e1bbbf71cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-styled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>29675ed0-cf6d-47c5-97bd-a30b4873e49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mounted</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f7d3a643-e825-4235-8239-beb343f08b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promise</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>30e5d3c9-cb6b-4518-8b4a-2be7fcbc1563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-removed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f6a01624-789b-4ded-94b8-ca03ff821286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>74b5145f-8b54-4abf-a396-a6d1dfc0406b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-y-position</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>a6b6f627-f3cb-4655-a335-795fd5792ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-x-position</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>3a481734-b6c8-4b3c-b41c-dc79346cefc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a79e04d2-f8f0-45d2-8b8f-e2b996428b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-front</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>84839b55-87c1-4387-bfd5-260fbf345ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swiping</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7390a683-6020-41dd-ab36-8608e983e149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismissible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98936eae-5b0a-425c-ae77-6deb8170f5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>3d72d20a-f1cc-4526-bbeb-997b66462da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swipe-out</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>40b2787f-7210-49ad-984d-42cb26efc0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0ade8b9-56e5-474d-b886-5dd35b3d3556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email sudah terdaftar</value>
      <webElementGuid>7bb4ef86-184e-421c-a7e4-3704ef458e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[1]/ol[1]/li[1]</value>
      <webElementGuid>090b5eca-c201-4fad-963b-a09b2fe6df0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/ol/li</value>
      <webElementGuid>2f243980-5063-416d-9709-56ac2547b72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Akun Baru'])[1]/preceding::li[1]</value>
      <webElementGuid>27f1450d-1dc7-4d69-bd68-02a636b8d377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>d5b3227f-7735-40a8-9bdf-9e39d2f6f158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Email sudah terdaftar' or . = 'Email sudah terdaftar')]</value>
      <webElementGuid>9a9d1b39-fd78-4b37-9fda-08d39d38cef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
