<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_2024 Metrodata Academy. All right reserve_5ae0fa</name>
   <tag></tag>
   <elementGuidId>973c9e6b-1575-4f52-b224-bee90d6d38f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/footer/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c0540ba8-dc5b-48f6-9a32-612ee31ec9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-normal leading-6 text-center text-[#888]</value>
      <webElementGuid>38aa2d8e-3541-4a10-aa83-31c6950f0393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>© 2024 Metrodata Academy. All right reserved by PT Mitra Integrasi Informatika.</value>
      <webElementGuid>891691bb-4433-43fc-a9cb-2dfe2ec4cf4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/footer[@class=&quot;bg-cerulean-50&quot;]/div[@class=&quot;py-8 pb-10 border-t border-gray-200&quot;]/p[@class=&quot;text-base font-normal leading-6 text-center text-[#888]&quot;]</value>
      <webElementGuid>8367d8a2-d31e-46a7-9db0-bc0a22fb99ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/footer/div[2]/p</value>
      <webElementGuid>15749557-6429-4c74-a0df-c8668b42353e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[1]/following::p[1]</value>
      <webElementGuid>b22dceb0-d323-4911-a6a1-770b068d4b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/following::p[1]</value>
      <webElementGuid>8ba4d8c5-0090-40cc-94dd-b93a24c33ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='©']/parent::*</value>
      <webElementGuid>d74e1701-a488-46c3-b64c-09a5223b4448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div[2]/p</value>
      <webElementGuid>5811dd9d-282b-430c-b68d-7b9df366641e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '© 2024 Metrodata Academy. All right reserved by PT Mitra Integrasi Informatika.' or . = '© 2024 Metrodata Academy. All right reserved by PT Mitra Integrasi Informatika.')]</value>
      <webElementGuid>54a10279-8bdc-416c-8d95-a803ad032cf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
